#!/bin/bash

_dq_usage() {
  echo "Usage: $(basename $0) [group]"
  echo "       $(basename $0) {-h|--help}"
  exit 0
}

BIN_DIR=$(dirname $0)
LIB_DIR=$BIN_DIR/lib

OK=0
KO=0

_dq_report () {
  if [ "$2" -eq 0 ]; then
    echo "✔ $1"
    OK=$(($OK+1))
  else
    echo "✘ $1"
    KO=$(($KO+1))
  fi
}

_dq_source() {
  if [ -d "$LIB_DIR" -o -h "$LIB_DIR" ]; then
    _dq_source_local "$1"
  else
    _dq_source_remote "$1"
  fi
}

_dq_source_local() {
  for script in $(ls $LIB_DIR/${1}.sh); do
    source $script
  done
}

_dq_source_remote() {
  echo "ERROR! No local sources!"
  exit 100
}

case ${1:-core} in
  -h|--help)
    _dq_usage
    ;;
  all)
    _dq_source '*/*'
    ;;
  core)
    _dq_source 'core/*'
    ;;
  java_dev)
    _dq_source 'core/java'
    _dq_source 'java/*'
    ;;
  clojure_dev)
    _dq_source 'core/java'
    _dq_source 'clojure/*'
    ;;
  groovy_dev)
    _dq_source 'core/java'
    _dq_source 'java/gradle'
    _dq_source 'groovy/*'
    ;;
  scala_dev)
    _dq_source 'core/java'
    _dq_source 'scala/*'
    ;;
  ruby_dev)
    _dq_source 'core/ruby'
    _dq_source 'ruby/*'
    ;;
  frontend_dev)
    _dq_source 'core/*'
    _dq_source 'frontend/*'
    ;;
  db)
    _dq_source 'db/*'
    ;;
esac


echo Your dq is $OK / $(($OK+$KO))

exit $KO
